USE [master]
GO

/****** Object:  Database [DigitalVaultDB]    Script Date: 9/23/2026 3:48:32 PM ******/
CREATE DATABASE [DigitalVaultDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DigitalVaultDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DigitalVaultDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DigitalVaultDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DigitalVaultDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DigitalVaultDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DigitalVaultDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DigitalVaultDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DigitalVaultDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DigitalVaultDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DigitalVaultDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DigitalVaultDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DigitalVaultDB] SET  MULTI_USER 
GO

ALTER DATABASE [DigitalVaultDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DigitalVaultDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DigitalVaultDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DigitalVaultDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DigitalVaultDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DigitalVaultDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DigitalVaultDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DigitalVaultDB] SET  READ_WRITE 
GO

